version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: marketflow-rabbitmq
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - marketflow-net

  redis:
    image: redis:7
    container_name: marketflow-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - marketflow-net

  postgres:
    image: postgres:17
    container_name: marketflow-postgres
    env_file: .env
    ports: 
      - "55432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketflow -d marketflow"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - marketflow-net

networks:
  marketflow-net:

volumes:
  pgdata:
  redisdata: