[project]
name="marketflow-api"
version="0.1.0"
dependencies=[
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "marketflow-common",
  "httpx"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "httpx"
]