[project]
name = "marketflow-ingestion"
version = "0.1.1"
dependencies = [
  "fastapi",
  "uvicorn",
  "pydantic",
  "marketflow-common",
  "httpx",
  "yfinance"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio"
]