[project]
name = "marketflow-etl"
version = "0.1.0"
dependencies = [
  "sqlalchemy>=2.0",
  "psycopg2-binary",
  "pydantic>=2.5",
  "marketflow-common"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov"
]